# Generated by Django 4.1.6 on 2023-08-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_user_login_user_firstname_user_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.category'),
        ),
    ]
